sudo: required

dist: xenial

language: ruby

rvm: 2.6.5

node_js: 12.13.0

jdk: openjdk8

addons:
  postgresql: 10

before_install:
  - sudo apt-get -qq update
  - sudo rm -f /usr/share/ca-certificates/mozilla/AddTrust_External_Root.crt
  - sudo update-ca-certificates -f -v
  - sudo apt-get install -y postgresql-10-postgis-2.4 gdal-bin proj-bin libgeos-dev libgeos++-dev libproj-dev ffmpeg
  - psql -U postgres -c "create extension postgis"
  - psql -U postgres -c 'create extension "uuid-ossp"'
  - createdb -O postgres template_postgis
  - psql -U postgres template_postgis -c "UPDATE pg_database SET datistemplate = TRUE WHERE datname = 'template_postgis'"
  - export JAVA_HOME='/usr'
  - curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.1-linux-x86_64.tar.gz | tar xz -C /tmp
  - /tmp/elasticsearch-7.3.1/bin/elasticsearch-keystore create
  - /tmp/elasticsearch-7.3.1/bin/elasticsearch-plugin install analysis-kuromoji
  - /tmp/elasticsearch-7.3.1/bin/elasticsearch -E http.port=9200 -d
  - gem install bundler
  - mkdir -p tmp/pids
  - echo -e "--format documentation\n--color\n--require spec_helper\n--profile\n--tty" > .rspec
  - nvm install 12.13.0
  - node --version
  - npm --version
  - nvm --version
  - npm ci

before_script:
  - sleep 25
  - ci/scripts/before_script.sh

env:
  - TRAVIS_CI=true TESTFOLDER=spec/models/*(observation|taxon)_spec.rb
  - TRAVIS_CI=true TESTFOLDER=spec/models/*(identification|project_observation|project|user)_spec.rb
  - TRAVIS_CI=true TESTFOLDER=spec/models/!(observation|taxon|identification|project_observation|project|user)_spec.rb
  - TRAVIS_CI=true TESTFOLDER='spec/controllers'
  - TRAVIS_CI=true TESTFOLDER='spec/helpers spec/initializers spec/lib spec/views'

script: "bundle exec rspec $TESTFOLDER"

notifications:
  slack:
    secure: a5oKH3x+irU27B+5f9hZPLEKl4gFPjj74UXPvVPKJdJ8shnDVwZkJdzsCV9u2qirD07TzZNCKGprTIG4zWJdYyMVmKucwT7hRMPCGIBu/2cGvSBfOSyiDHLNmvUvA6yOaECWT7h8CpTE2wqxNV8avqGlc20oNrxlJT2bpVTTU4U=

branches:
  except:
    - l10n_master
